language: python

env:
    global:
        # Set defaults to avoid repeating in most cases
        - NUMPY_VERSION=1.13
        - ANSWER_VER=pyxsim18
        - TEST_OPTS="--nologcapture -sv --with-answer-testing --local --local-dir ."
matrix:
    include:

        - python: 3.5
          env: CMD="nosetests ${TEST_OPTS} --answer-name=${ANSWER_VER}_3 pyxsim/tests --with-coverage --cover-package=pyxsim"; PYTHON='python3.5'
        - python: 3.6
          env: CMD="nosetests ${TEST_OPTS} --answer-name=${ANSWER_VER}_3 pyxsim/tests"; PYTHON='python3.6'

before_install:

    - wget http://yt-project.org/data/enzo_tiny_cosmology.tar.gz
    - tar -zxvf enzo_tiny_cosmology.tar.gz
    - wget http://yt-project.org/data/GasSloshingLowRes.tar.gz
    - tar -zxvf GasSloshingLowRes.tar.gz
    - wget http://yt-project.org/data/FIRE_M12i_ref11.tar.gz
    - tar -zxvf FIRE_M12i_ref11.tar.gz
    - wget http://hea-www.cfa.harvard.edu/~jzuhone/${ANSWER_VER}_2.tar.gz
    - tar -zxvf ${ANSWER_VER}_2.tar.gz		
    - wget http://hea-www.cfa.harvard.edu/~jzuhone/${ANSWER_VER}_3.tar.gz
    - tar -zxvf ${ANSWER_VER}_3.tar.gz		
    - mkdir -p ~/.config/yt
    - printf "[yt]\ntest_data_dir = $PWD" >> $HOME/.config/yt/ytrc
    - wget http://hea-www.cfa.harvard.edu/~jzuhone/soxs_responses.tar.gz
    - tar -zxvf soxs_responses.tar.gz
    - mkdir -p $HOME/.config/soxs
    - printf "[soxs]\nresponse_path = $PWD/soxs_responses" >> $HOME/.config/soxs/soxs.cfg    
    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

    # UPDATE APT-GET LISTINGS
    - sudo apt-get update

install:

    # CONDA
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - conda config --add channels https://conda.anaconda.org/sherpa
    - conda config --add channels conda-forge
    - conda install --yes numpy=$NUMPY_VERSION nose pip yt astropy sherpa cython scipy pyembree==0.1.3
    - conda install --yes -c jzuhone -c astropy soxs

    # COVERAGE DEPENDENCIES
    - pip install coverage coveralls
    - $PYTHON setup.py develop

script:

    - $CMD

after_success:
    - if [[ $PYTHON == 'python3.6' ]]; then
          coveralls --rcfile='pyxsim/tests/coveragerc';
      fi
